(()=>{
'use strict';
const D=window.RK_DATA, TARGET={cal:2000,p:180,c:190,f:58}, START=83, STORE='rippedKitchenStateV2';
const $=id=>document.getElementById(id), $$=q=>[...document.querySelectorAll(q)];
const E={date:$('dateInput'),day:$('dayLabel'),training:$('trainingType'),hint:$('trainingHint'),mealList:$('mealList'),mealCount:$('mealCount'),steps:$('steps'),mins:$('mins'),water:$('water'),sleep:$('sleep'),weight:$('weight'),waist:$('waist'),pct:$('dailyPct'),bar:$('dailyBar'),check:$('checkStatus'),finalBanner:$('finalBanner'),finalText:$('finalText'),summary:$('summary'),history:$('historyBox'),recipeSelect:$('recipeSelect'),recipeBox:$('recipeBox'),prepBox:$('prepBox'),bodyDate:$('bodyDate'),bodyPhase:$('bodyPhase'),bodyWeight:$('bodyWeight'),bodyWaist:$('bodyWaist'),bodyDelta:$('bodyDelta'),bodyHistory:$('bodyHistory'),human:$('human'),definition:$('definition'),install:$('installApp')};
let state={}; try{state=JSON.parse(localStorage.getItem(STORE)||'{}')||{}}catch(_){state={}}
let deferredInstall=null;
const todayISO=()=>{const d=new Date(),off=d.getTimezoneOffset();return new Date(d.getTime()-off*60000).toISOString().slice(0,10)};
const weekday=iso=>['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'][new Date(iso+'T12:00:00').getDay()];
const blank=()=>({meals:[],tasks:{},steps:8000,mins:60,water:3,sleep:8,training:'gym',weight:null,waist:null,final:null});
const key=()=>E.date.value;
const st=()=>{if(!state[key()])state[key()]=blank();return state[key()]};
const persist=()=>localStorage.setItem(STORE,JSON.stringify(state));
function moveDate(n){const d=new Date(key()+'T12:00:00');d.setDate(d.getDate()+n);E.date.value=d.toISOString().slice(0,10);renderAll()}
function totals(){const t={cal:0,p:0,c:0,f:0};D.plans[weekday(key())].forEach((m,i)=>{if(st().meals.includes(i)){t.cal+=m[2];t.p+=m[3];t.c+=m[4];t.f+=m[5]}});return t}
function fill(id,v,max){$(id).style.height=Math.min(100,Math.max(0,v/max*100))+'%'}
function renderMeals(){const s=st(),t=totals();E.mealList.innerHTML='';D.plans[weekday(key())].forEach((m,i)=>{const done=s.meals.includes(i),card=document.createElement('article');card.className='card meal'+(done?' done':'');card.setAttribute('aria-pressed',done?'true':'false');card.innerHTML=`<div class="meal-head"><div><h3>${m[0]}</h3><div class="meal-meta">${m[2]} kcal · P ${m[3]}g · C ${m[4]}g · F ${m[5]}g</div><button class="recipe-link" data-recipe="${m[1]}">Full recipe</button><div class="small muted" style="margin-top:8px">${done?'Completed ✓ — tap card to undo':'Tap card when finished'}</div></div>${done?'<span class="badge">Done ✓</span>':''}</div>`;
card.addEventListener('click',e=>{if(e.target.closest('[data-recipe]'))return;const x=s.meals.indexOf(i);x>=0?s.meals.splice(x,1):s.meals.push(i);persist();renderMeals()});
card.querySelector('[data-recipe]').addEventListener('click',e=>{e.stopPropagation();E.recipeSelect.value=e.currentTarget.dataset.recipe;renderRecipe();showPage('recipes')});E.mealList.appendChild(card)});
E.mealCount.textContent=`${s.meals.length} / 5 done`; $('calVal').textContent=`${t.cal} / 2000`; $('proVal').textContent=`${t.p} / 180g`; $('carbVal').textContent=`${t.c} / 190g`; $('fatVal').textContent=`${t.f} / 58g`;fill('fillCal',t.cal,TARGET.cal);fill('fillPro',t.p,TARGET.p);fill('fillCarb',t.c,TARGET.c);fill('fillFat',t.f,TARGET.f)}
function renderTasks(){const s=st();$$('[data-task]').forEach(c=>c.checked=!!s.tasks[c.dataset.task]);E.steps.value=s.steps;E.mins.value=s.mins;E.water.value=s.water;E.sleep.value=s.sleep;const n=Object.values(s.tasks).filter(Boolean).length,p=Math.round(n/6*100);E.pct.textContent=p+'%';E.bar.style.width=p+'%'}
function burnEstimate(){const s=st(),w=s.weight||START,met={gym:6,mma:10,football:8.5,rest:0}[s.training]||0;const walking=s.steps*w*0.00038,training=met*3.5*w/200*s.mins;return Math.round(walking+training)}
function finaliseDay(){const s=st(),t=totals(),execution=Math.round(Object.values(s.tasks).filter(Boolean).length/6*100);s.final={savedAt:new Date().toISOString(),cal:t.cal,p:t.p,c:t.c,f:t.f,meals:s.meals.length,execution,burn:burnEstimate(),weight:s.weight,waist:s.waist,training:s.training,steps:s.steps,mins:s.mins,water:s.water,sleep:s.sleep,tasks:{...s.tasks},mealIndexes:[...s.meals]};persist();renderFinal();renderHistory()}
function renderFinal(){const f=st().final;E.finalBanner.classList.toggle('hidden',!f);E.summary.classList.toggle('hidden',!f);if(!f)return;E.finalText.textContent=`${f.meals}/5 meals · ${f.cal} kcal · ${f.p}g protein · ${f.execution}% execution`;E.summary.innerHTML=`<article class="card"><span class="muted">Calories</span><strong>${f.cal}</strong></article><article class="card"><span class="muted">Protein</span><strong>${f.p}g</strong></article><article class="card"><span class="muted">Activity</span><strong>~${f.burn}</strong></article><article class="card"><span class="muted">Execution</span><strong>${f.execution}%</strong></article>`}
function renderHistory(){const keys=Object.keys(state).filter(k=>state[k].final).sort().reverse();E.history.innerHTML=keys.length?keys.slice(0,30).map(k=>{const f=state[k].final;return `<button data-history="${k}"><span>${k}</span><span>${f.weight?Number(f.weight).toFixed(1)+'kg':'—'}</span><span>${f.cal} kcal</span><span>${f.execution}%</span></button>`}).join(''):'<p class="small muted">No finalised days yet.</p>';$$('[data-history]').forEach(b=>b.addEventListener('click',()=>{E.date.value=b.dataset.history;renderAll();showPage('home');window.scrollTo({top:0,behavior:'smooth'})}))}
function renderRecipe(){const r=D.recipes[E.recipeSelect.value];if(!r)return;E.recipeBox.innerHTML=`<div class="stack"><div class="recipe-macros"><article class="card"><span class="muted">Calories</span><strong>${r.m[0]}</strong></article><article class="card"><span class="muted">Protein</span><strong>${r.m[1]}g</strong></article><article class="card"><span class="muted">Carbs</span><strong>${r.m[2]}g</strong></article><article class="card"><span class="muted">Fat</span><strong>${r.m[3]}g</strong></article></div><article class="card"><h2>${r.name}</h2><p class="small muted" style="margin:6px 0 14px">Working macro estimate; exact values depend on your product labels.</p><h3>Exact ingredients</h3>${r.ingredients.map(x=>`<div class="row"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('')}<h3 style="margin-top:20px">Step-by-step method</h3>${r.steps.map((x,i)=>`<div class="step"><div class="stepnum">${i+1}</div><div>${x}</div></div>`).join('')}</article></div>`}
function renderPrep(which){$$('[data-prep]').forEach(b=>b.classList.toggle('active',b.dataset.prep===which));const p=D.prep[which];E.prepBox.innerHTML=`<div class="stack"><article class="card"><h2>${p.title}</h2><h3>Batch ingredients and quantities</h3>${p.batch.map(x=>`<div class="row"><div><div>${x[0]}</div><div class="small muted">${x[2]}</div></div><strong>${x[1]}</strong></div>`).join('')}</article><article class="card"><h2>Pack each container exactly like this</h2><div class="pack-grid">${p.boxes.map(x=>`<div class="pack"><div style="display:flex;gap:10px"><div class="packnum">${x[0]}</div><div><strong>${x[1]}</strong><div class="small muted" style="margin-top:4px">${x[2]}</div></div></div></div>`).join('')}</div></article><article class="card"><h2>Step-by-step prep workflow</h2>${p.steps.map((x,i)=>`<div class="step"><div class="stepnum">${i+1}</div><div>${x}</div></div>`).join('')}</article></div>`}
function renderBody(){const s=st(),w=s.weight||START,delta=w-START,p=Math.min(1,Math.max(0,(START-w)/8));E.bodyDate.textContent=`${key()} · ${weekday(key())}`;E.bodyWeight.value=w;E.bodyWaist.value=s.waist||'';E.bodyDelta.textContent=(delta>=0?'+':'')+delta.toFixed(1)+'kg';E.bodyPhase.textContent=p<.2?'Starting phase':p<.5?'Leaning out':p<.8?'Defined phase':'Ripped phase';E.human.style.transformOrigin='160px 260px';E.human.style.transform=`scaleX(${1-p*.07})`;E.definition.style.opacity=String(.4+p*.5);const keys=Object.keys(state).filter(k=>state[k].weight).sort().reverse();E.bodyHistory.innerHTML=keys.length?keys.slice(0,20).map(k=>`<div class="row"><span>${k}</span><span>${Number(state[k].weight).toFixed(1)}kg${state[k].waist?' · '+Number(state[k].waist).toFixed(1)+'cm':''}</span></div>`).join(''):'<p class="small muted">No check-ins saved yet.</p>'}
function showPage(name){$$('.page').forEach(p=>p.classList.remove('active'));$(name).classList.add('active');$$('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===name));if(name==='body')renderBody();if(name==='recipes')renderRecipe();window.scrollTo({top:0,behavior:'smooth'})}
function renderAll(){const s=st();E.day.textContent=weekday(key());E.training.value=s.training;E.hint.textContent={gym:'Gym day: place a carb-containing meal 1–3 hours before training, then protein + carbs afterwards.',mma:'MMA day: prioritise COR, rice or banana before the session, keep pre-session fats lower and hydrate well.',football:'Football day: prioritise carbohydrates before and after, plus extra fluids.',rest:'Rest day: keep the baseline calories steady during the initial phase.'}[s.training];E.weight.value=s.weight??START;E.waist.value=s.waist??'';E.check.textContent=s.weight?`Saved: ${Number(s.weight).toFixed(1)}kg${s.waist?' · '+Number(s.waist).toFixed(1)+'cm':''}`:'';renderMeals();renderTasks();renderFinal();renderHistory();renderBody()}
E.date.value=todayISO();Object.entries(D.recipes).forEach(([k,r])=>{const o=document.createElement('option');o.value=k;o.textContent=r.name;E.recipeSelect.appendChild(o)});E.recipeSelect.value='oats';
$('prevDate').addEventListener('click',()=>moveDate(-1));$('nextDate').addEventListener('click',()=>moveDate(1));E.date.addEventListener('change',renderAll);E.training.addEventListener('change',()=>{st().training=E.training.value;persist();renderAll()});$$('[data-task]').forEach(c=>c.addEventListener('change',()=>{st().tasks[c.dataset.task]=c.checked;persist();renderTasks()}));[['steps','steps'],['mins','mins'],['water','water'],['sleep','sleep']].forEach(([id,k])=>$(id).addEventListener('input',e=>{st()[k]=parseFloat(e.target.value)||0;persist()}));$('saveCheckin').addEventListener('click',()=>{st().weight=parseFloat(E.weight.value)||null;st().waist=parseFloat(E.waist.value)||null;persist();renderAll()});$('bodySave').addEventListener('click',()=>{st().weight=parseFloat(E.bodyWeight.value)||null;st().waist=parseFloat(E.bodyWaist.value)||null;persist();renderAll()});$('finalise').addEventListener('click',finaliseDay);$('resetDay').addEventListener('click',()=>{if(confirm('Reset everything for this selected date?')){state[key()]=blank();persist();renderAll()}});E.recipeSelect.addEventListener('change',renderRecipe);$$('[data-prep]').forEach(b=>b.addEventListener('click',()=>renderPrep(b.dataset.prep)));$$('.bottom-nav button').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.page)));
const deadline=new Date('2026-12-15T00:00:00');$('countdown').textContent=Math.max(0,Math.ceil((deadline-new Date())/86400000))+' days';
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;E.install.classList.remove('hidden')});E.install.addEventListener('click',async()=>{if(!deferredInstall)return;deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;E.install.classList.add('hidden')});window.addEventListener('appinstalled',()=>E.install.classList.add('hidden'));
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
renderAll();renderRecipe();renderPrep('sun');
})();