window.RK_BULK_PREP={
 sun:{time:'About 90–110 minutes',start:['Put Containers 1–5 in a row and label them before cooking.','Keep raw chicken/fish away from cooked food. After handling raw meat, wash hands and use a clean board, knife and plate for cooked food.','For chicken/mince, use a thermometer if possible: 75°C for at least 30 seconds in the centre, or 70°C for 2 minutes. Without one, check the thickest part is steaming hot throughout with no raw-looking centre.','Weigh about 800g raw chicken and split it: 400g tandoori for Boxes 1+5, 200g tikka for Box 2, 200g karahi for Box 3.','Measure everything before heating pans: about 160g dry rice, 500g raw potatoes, 180g raw salmon, vegetables, yoghurt, lemon, spices and oil.','Marinate tandoori and tikka first. Then start rice and potatoes. Cook chicken while they cook, make karahi next, salmon last, vegetables at the end.'],dishes:[
  {n:'Tandoori chicken — Boxes 1 & 5',m:'Makes 300g cooked chicken: 150g per box',i:[['Raw chicken breast','400g'],['0% Greek yoghurt','50g'],['Lemon juice','20g'],['Garlic','10g / ~2 cloves'],['Fresh ginger','10g'],['Tandoori masala','2 tsp'],['Kashmiri chilli','1 tsp'],['Ground cumin','1 tsp'],['Ground coriander','1 tsp'],['Turmeric','1/2 tsp'],['Salt + black pepper','to taste']],s:['Trim the chicken. If pieces are very thick, slice them so they are similar thickness.','Mix yoghurt, lemon, garlic, ginger and spices in a bowl until smooth.','Add 400g chicken and coat every surface. Refrigerate at least 30 minutes.','Air fryer: preheat 185°C for 3 minutes. Put chicken in one layer. Cook 6–8 minutes, turn, then another 6–8 minutes. If crowded, cook in 2 batches.','Oven alternative: 200°C / 180°C fan for about 18–25 minutes.','Cooking time varies with thickness. Check the centre is fully cooked using the temperature rule above.','Move to a clean plate and rest 5 minutes.','Tare the scales. Weigh exactly 150g cooked chicken for Box 1 and 150g for Box 5. Keep any extra separate.']},
  {n:'Chicken tikka — Box 2',m:'Makes 150g cooked chicken',i:[['Raw chicken breast','200g'],['0% Greek yoghurt','25g'],['Lemon juice','10g'],['Garlic','5g / ~1 clove'],['Tikka/tandoori masala','1 tsp'],['Normal/sweet paprika','1/2 tsp'],['Ground cumin','1/2 tsp'],['Salt + pepper','to taste']],s:['Mix yoghurt, lemon, garlic and spices.','Coat the 200g chicken and refrigerate at least 30 minutes.','Air fry at 185°C for 12–16 minutes total, turning halfway, or bake at 200°C / 180°C fan for 18–25 minutes.','Check the thickest part is fully cooked, then rest 5 minutes on a clean plate.','Weigh exactly 150g cooked tikka chicken for Box 2.']},
  {n:'Lean chicken karahi — Box 3',m:'Makes 1 complete karahi portion',i:[['Raw chicken breast','200g'],['Tomatoes','200g diced'],['Onion','50g sliced'],['Olive oil','5g EXACT'],['Garlic','10g / ~2 cloves'],['Fresh ginger','8g'],['Green chilli','1'],['Ground cumin','1/2 tsp'],['Kashmiri chilli','1/2 tsp'],['Garam masala','1/2 tsp'],['Fresh coriander','10g'],['Salt + pepper','to taste']],s:['Cook the 200g chicken separately first until fully cooked. Rest 5 minutes.','Weigh exactly 150g cooked chicken and cut it into bite-size pieces.','Heat a non-stick pan on medium. Measure exactly 5g oil into the pan.','Add 50g onion and cook 4–6 minutes until soft. If it sticks, add a tablespoon of water, not extra oil.','Add garlic, ginger and chilli. Stir 30–45 seconds.','Add 200g tomatoes, cumin, Kashmiri chilli, salt and pepper. Cook uncovered 8–12 minutes, stirring regularly, until thick rather than watery.','Add the measured 150g cooked chicken and stir 2–3 minutes until coated and steaming hot.','Turn heat off. Stir in garam masala and 10g coriander. The whole pan is the Box 3 karahi portion.']},
  {n:'Basmati rice — Boxes 1, 3 & 5',m:'Need 430g cooked: 150g + 130g + 150g',i:[['Dry basmati rice','about 160g'],['Cold water','about 240ml + rinsing water']],s:['Weigh about 160g dry rice.','Rinse 3–5 times in cold water until the water is much less cloudy. Drain well.','Put rice in a saucepan with about 240ml cold water. Cover with a lid.','Bring to a boil, then immediately turn to the lowest heat.','Cook covered for 10 minutes. Do not keep lifting the lid.','Turn heat off and leave covered for another 10 minutes.','Fluff with a fork and weigh the cooked rice. You need at least 430g; if your brand yields less, cook a little extra rather than shrinking portions.','Pack exactly 150g into Box 1, 130g into Box 3 and 150g into Box 5.']},
  {n:'Potatoes — Boxes 2 & 4',m:'Need 400g cooked: 200g each',i:[['Raw potatoes','about 500g'],['Salt + pepper','to taste'],['Paprika/cumin','optional; no free-poured oil']],s:['Wash about 500g potatoes and cut into roughly 2cm cubes or equal wedges.','Put into boiling water for 7–8 minutes. Drain and let steam-dry for 5 minutes.','Air fry 190°C for 18–22 minutes, shaking halfway, or oven-roast 210°C / 190°C fan for 25–35 minutes, turning once.','Do not pour oil over them. The planned oil is measured when packing.','Weigh exactly 200g cooked potato into Box 2 and 200g into Box 4.']},
  {n:'Masala salmon — Box 4',m:'Makes 140–150g cooked salmon',i:[['Raw salmon','about 180g'],['Lemon juice','10g'],['Garlic','5g'],['Kashmiri chilli','1/2 tsp'],['Ground cumin','1/2 tsp'],['Normal/sweet paprika','1/2 tsp'],['Salt + pepper','to taste']],s:['Pat salmon dry.','Mix lemon, garlic and spices and coat the salmon. No added oil.','Rest 10–20 minutes.','Air fry 180°C for 8–11 minutes or bake 200°C / 180°C fan for 10–14 minutes. Thick pieces can take longer.','The centre should be opaque and flake easily. Rest 2–3 minutes.','Weigh 140–150g cooked salmon into Box 4.']},
  {n:'Vegetables — Boxes 1, 2, 4 & 5',m:'Need 800g cooked vegetables total',i:[['Broccoli/green beans/peppers/mixed veg','enough to yield 800g cooked']],s:['Cut large vegetables into similar-size pieces.','Steam, microwave or boil until tender but not mushy. Broccoli/green beans usually need roughly 5–7 minutes once steaming/boiling.','Drain very well.','Weigh exactly 200g cooked vegetables into Boxes 1, 2, 4 and 5. If you have less than 800g after cooking, cook more rather than under-filling the boxes.']}
 ],finish:['Box 1: 150g rice + 150g tandoori chicken + 200g veg + exactly 5g olive oil.','Box 2: 150g tikka chicken + 200g potato + 200g veg + exactly 5g olive oil.','Box 3: whole measured karahi + exactly 130g rice. Karahi already contains its 5g oil.','Box 4: 140–150g salmon + 200g potato + 200g greens. No default extra oil.','Box 5: 150g rice + 150g tandoori chicken + 200g veg + exactly 5g olive oil.'],store:['Cool food quickly and get it into the fridge/freezer within 2 hours. Cool rice especially quickly; aim for within 1 hour.','Keep the Monday boxes refrigerated.','Freeze later meals rather than leaving all Sunday food refrigerated for several days. Freeze Box 3 and Box 5 once cooled; freeze Box 4 too if it will not be eaten within 48 hours.','Move frozen meals to the fridge the night before eating.','Reheat only once and until steaming hot throughout. Stir rice during microwave reheating so there are no cold pockets.']},
 wed:{time:'About 75–95 minutes',start:['Put five clean containers in a row and label them.','For chicken/mince, use a thermometer if possible: 75°C for at least 30 seconds in the centre, or 70°C for 2 minutes.','Measure about 650–700g raw chicken, 200g raw 5% mince, 220g raw cod/haddock, 105g dry rice, 280g raw potatoes and enough vegetables to yield about 800g cooked.','Use about 400g raw chicken for Boxes 1+5 and about 200g raw chicken for Box 4. Any cooked surplus stays separate.','Start rice and potatoes first. Make keema while chicken marinates. Cook chicken next, white fish last, then vegetables.'],dishes:[
  {n:'Masala chicken — Boxes 1 & 5',m:'Makes 300g cooked chicken: 150g each',i:[['Raw chicken breast','about 400g'],['0% Greek yoghurt','40g'],['Lemon juice','20g'],['Garlic','10g'],['Normal/sweet paprika','1 tsp'],['Ground cumin','1 tsp'],['Ground coriander','1 tsp'],['Kashmiri chilli','1/2–1 tsp'],['Turmeric','1/4 tsp'],['Salt + pepper','to taste']],s:['Mix yoghurt, lemon, garlic and spices.','Coat chicken and marinate 20–30 minutes.','Air fry 185°C for 12–16 minutes total, turning halfway, or bake 200°C / 180°C fan for 18–25 minutes.','Check fully cooked, rest 5 minutes, then weigh 150g into Box 1 and 150g into Box 5.','Do not add rice to these boxes. Cream of Rice is made fresh when you eat them.']},
  {n:'Lean keema — Box 2',m:'Makes the complete keema portion',i:[['5% beef mince or lean turkey mince','200g raw'],['Tomatoes','150g'],['Onion','50g'],['Peas','50g'],['Olive oil','5g EXACT'],['Garlic','10g'],['Fresh ginger','8g'],['Green chilli','1'],['Ground cumin','1/2 tsp'],['Ground coriander','1/2 tsp'],['Turmeric','1/4 tsp'],['Garam masala','1/2 tsp'],['Salt + pepper','to taste']],s:['Heat a wide non-stick pan on medium and add exactly 5g oil.','Cook 50g onion for 4–6 minutes.','Add garlic, ginger and chilli for 30–45 seconds.','Add 200g mince. Break it into small pieces and cook 6–8 minutes, stirring often.','Add tomatoes, cumin, coriander, turmeric, salt and pepper. Cook 8–10 minutes until thick.','Add 50g peas and cook 3–4 minutes.','Stir in garam masala. Make sure mince is thoroughly cooked and steaming hot throughout.','Weigh 150g cooked keema for Box 2 and keep the planned tomato/pea masala with it.']},
  {n:'Tandoori chicken — Box 4',m:'Makes 150g cooked chicken',i:[['Raw chicken breast','about 200g'],['0% Greek yoghurt','25g'],['Lemon juice','10g'],['Garlic','5g'],['Fresh ginger','5g'],['Tandoori masala','1 tsp'],['Kashmiri chilli','1/2 tsp'],['Ground cumin','1/2 tsp'],['Ground coriander','1/2 tsp'],['Turmeric','1/4 tsp'],['Salt + pepper','to taste']],s:['Mix marinade and coat chicken. Marinate at least 30 minutes.','Air fry 185°C for 12–16 minutes, turning halfway, or bake 200°C / 180°C fan for 18–25 minutes.','Check fully cooked, rest 5 minutes and weigh exactly 150g cooked chicken into Box 4.']},
  {n:'Basmati rice — Boxes 2 & 4',m:'Need 270g cooked: 120g + 150g',i:[['Dry basmati rice','about 105g'],['Cold water','about 160ml + rinsing water']],s:['Rinse 105g rice 3–5 times and drain.','Add about 160ml cold water, cover and bring to a boil.','Turn to the lowest heat and cook covered for 10 minutes.','Turn heat off, leave covered 10 minutes, then fluff.','Pack exactly 120g cooked rice into Box 2 and 150g into Box 4. If yield is short, cook a small extra amount.']},
  {n:'Masala white fish — Box 3',m:'Makes 170–180g cooked fish',i:[['Cod/haddock','about 220g raw'],['Lemon juice','10g'],['Garlic','5g'],['Kashmiri chilli','1/2 tsp'],['Turmeric','1/4 tsp'],['Ground cumin','1/2 tsp'],['Ground coriander','1/2 tsp'],['Salt + pepper','to taste']],s:['Pat fish dry. Mix lemon, garlic and spices and coat both sides.','Rest 10 minutes.','Air fry 180°C for 8–11 minutes or bake 200°C / 180°C fan for 10–14 minutes.','Fish should be opaque through the centre and flake easily.','Rest 2 minutes and weigh 170–180g cooked fish into Box 3.']},
  {n:'Potato + vegetable batch',m:'225g cooked potato for Box 3; 800g cooked veg across 4 boxes',i:[['Raw potatoes','about 280g'],['Vegetables/greens','enough to yield 800g cooked'],['Olive oil','5g Box 3 + 5g Box 4']],s:['Cut potatoes into 2cm pieces. Parboil 7–8 minutes, drain and steam-dry 5 minutes.','Air fry 190°C for 18–22 minutes or roast 210°C / 190°C fan for 25–35 minutes.','Weigh exactly 225g cooked potato into Box 3.','Steam/microwave vegetables until tender-crisp and drain well.','Weigh 200g veg into Boxes 1, 3, 4 and 5.','Add exactly 5g oil to Box 3 and exactly 5g oil to Box 4. Keema already used its own separate 5g oil.']}
 ],finish:['Box 1: 150g masala chicken + 200g greens. Make COR fresh.','Box 2: 150g cooked keema + exactly 120g cooked rice.','Box 3: 170–180g white fish + 225g potato + 200g veg + exactly 5g oil.','Box 4: 150g tandoori chicken + 150g rice + 200g veg + exactly 5g oil.','Box 5: 150g masala chicken + 200g greens. Make COR fresh.'],store:['Cool and refrigerate/freeze promptly, within 2 hours; cool rice especially quickly.','Box 1 is for Wednesday and can be refrigerated. Boxes 2 and 3 are for Thursday and can be refrigerated.','Freeze Box 4 once cooled because it contains Friday rice; move it to the fridge Thursday night. Freeze Box 5 too if it would otherwise sit beyond 48 hours.','Reheat only once and until steaming hot throughout.']},
 fri:{time:'About 65–85 minutes',start:['Set Containers 1–4 out and keep Container 5 clean as the spare.','For chicken, use a thermometer if possible: 75°C for at least 30 seconds in the centre, or 70°C for 2 minutes.','Measure about 450–500g raw chicken, 180g raw salmon, 500g raw potatoes, 50g dry rice and vegetables to yield about 600g cooked.','Split chicken roughly: 200g Saturday tikka, 200g Sunday karahi; use any extra for Box 4 if you want the flexible chicken + greens meal.','Start rice and potatoes first. Marinate tikka, prepare karahi, cook chicken, make karahi, salmon last, vegetables at the end.'],dishes:[
  {n:'Saturday chicken tikka — Box 1',m:'Makes 150g cooked chicken',i:[['Raw chicken breast','about 200g'],['0% Greek yoghurt','25g'],['Lemon juice','10g'],['Garlic','5g'],['Tikka/tandoori masala','1 tsp'],['Normal/sweet paprika','1/2 tsp'],['Ground cumin','1/2 tsp'],['Salt + pepper','to taste']],s:['Mix marinade ingredients.','Coat chicken and marinate at least 30 minutes.','Air fry 185°C for 12–16 minutes, turning halfway, or bake 200°C / 180°C fan for 18–25 minutes.','Check fully cooked, rest 5 minutes, then weigh exactly 150g cooked chicken into Box 1.']},
  {n:'Sunday chicken karahi — Box 3',m:'Makes 1 complete karahi portion',i:[['Raw chicken breast','about 200g'],['Tomatoes','200g'],['Onion','50g'],['Olive oil','5g EXACT'],['Garlic','10g'],['Fresh ginger','8g'],['Green chilli','1'],['Ground cumin','1/2 tsp'],['Kashmiri chilli','1/2 tsp'],['Garam masala','1/2 tsp'],['Fresh coriander','10g'],['Salt + pepper','to taste']],s:['Cook chicken separately until fully cooked, rest 5 minutes, then weigh exactly 150g cooked chicken.','Heat a non-stick pan on medium and add exactly 5g oil.','Cook 50g onion for 4–6 minutes.','Add garlic, ginger and chilli for 30–45 seconds.','Add tomatoes, cumin, chilli, salt and pepper. Cook uncovered 8–12 minutes until thick.','Add the 150g cooked chicken and stir 2–3 minutes until steaming hot.','Turn off heat and stir in garam masala and coriander. The whole pan is Box 3 karahi.']},
  {n:'Weekend potatoes — Boxes 1 & 2',m:'Need 400g cooked: 200g each',i:[['Raw potatoes','about 500g']],s:['Cut into roughly 2cm pieces.','Parboil 7–8 minutes, drain and steam-dry 5 minutes.','Air fry 190°C for 18–22 minutes or roast 210°C / 190°C fan for 25–35 minutes, turning once.','Do not add unmeasured oil.','Weigh exactly 200g cooked potato into Box 1 and 200g into Box 2.']},
  {n:'Masala salmon — Box 2',m:'Makes 140–150g cooked salmon',i:[['Raw salmon','about 180g'],['Lemon juice','10g'],['Garlic','5g'],['Kashmiri chilli','1/2 tsp'],['Ground cumin','1/2 tsp'],['Normal/sweet paprika','1/2 tsp'],['Salt + pepper','to taste']],s:['Pat salmon dry and coat with lemon, garlic and spices. No added oil.','Rest 10–20 minutes.','Air fry 180°C for 8–11 minutes or bake 200°C / 180°C fan for 10–14 minutes.','When opaque and easily flaked, rest 2–3 minutes and weigh 140–150g cooked salmon into Box 2.']},
  {n:'Small basmati rice batch — Box 3',m:'Need 130g cooked rice',i:[['Dry basmati rice','about 50g'],['Cold water','about 75ml + rinsing water']],s:['Rinse 50g rice 3–5 times and drain.','Add about 75ml cold water, cover and bring to a boil.','Turn to lowest heat and cook covered for 10 minutes.','Turn heat off and leave covered 10 minutes, then fluff.','Weigh exactly 130g cooked rice for Box 3. If yield is short, make a little extra.']},
  {n:'Vegetables + flexible Box 4 chicken',m:'600g cooked veg; optional 150g cooked chicken in Box 4',i:[['Vegetables/greens','enough to yield 600g cooked'],['Extra raw chicken','enough to yield 150g cooked if using Box 4'],['Paprika + cumin + coriander','light seasoning'],['Olive oil','5g for Box 1; karahi has its own 5g']],s:['Steam/microwave vegetables until tender-crisp and drain well.','Weigh 200g veg into Boxes 1, 2 and 4.','If using Box 4 as chicken + greens, season extra chicken with paprika, cumin, coriander, salt and pepper. Cook alongside tikka but keep it separate.','Rest 5 minutes and weigh exactly 150g cooked chicken into Box 4.','Add exactly 5g olive oil to Box 1. Do not free-pour extra oil into the other boxes.']}
 ],finish:['Box 1: 150g tikka chicken + 200g potato + 200g veg + exactly 5g oil.','Box 2: 140–150g salmon + 200g potato + 200g greens.','Box 3: whole karahi + exactly 130g rice. Karahi already contains exactly 5g oil.','Box 4: 150g flexible chicken + 200g greens, or keep it for the planned savoury swap.','Box 5: clean and empty spare.'],store:['Cool food quickly and refrigerate/freeze within 2 hours. Cool rice especially quickly.','Saturday Boxes 1 and 2 can stay refrigerated.','Freeze Box 3 once cooled because its rice is for Sunday, then move it to the fridge Saturday night.','Freeze Box 4 too if it will not be eaten within 48 hours.','Reheat only once and until steaming hot throughout. Oats, eggs, yoghurt, fruit and COR are still made fresh.']}
};

if(window.RK_DATA&&window.RK_DATA.prep){
 const oil=(k,total,note)=>{const r=window.RK_DATA.prep[k]?.batch?.find(x=>x[0]==='Olive oil');if(r){r[1]=total;r[2]=note;}};
 oil('sun','20g total','5g each in Boxes 1, 2 and 5 + 5g used in karahi');
 oil('wed','15g total','5g keema + 5g fish box + 5g tandoori box');
 oil('fri','10g total','5g Saturday tikka box + 5g Sunday karahi');
}

(()=>{
 const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const steps=a=>a.map((x,i)=>`<div class="step"><div class="stepnum">${i+1}</div><div>${esc(x)}</div></div>`).join('');
 const rows=a=>a.map(x=>`<div class="row"><span>${esc(x[0])}</span><strong>${esc(x[1])}</strong></div>`).join('');
 function add(which){
  const box=document.getElementById('prepBox'),g=window.RK_BULK_PREP?.[which]; if(!box||!g)return;
  box.querySelector('[data-bulk]')?.remove(); const root=box.querySelector('.stack'); if(!root)return;
  const w=document.createElement('div'); w.className='stack'; w.dataset.bulk=which;
  w.innerHTML=`<article class="card stack"><div><h2>A–Z bulk cooking guide</h2><p class="muted" style="margin-top:6px">${esc(g.time)}</p></div><div class="callout"><strong>Raw vs cooked:</strong> raw batch amounts are what you start cooking with. The box map uses the final cooked weights. Always weigh the cooked portions.</div><div><h3>Before you start</h3>${steps(g.start)}</div></article>${g.dishes.map((d,i)=>`<details class="card" ${i===0?'open':''}><summary style="cursor:pointer;list-style:none;display:flex;justify-content:space-between;gap:12px"><div><strong>${esc(d.n)}</strong><div class="small muted" style="margin-top:5px">${esc(d.m)}</div></div><span class="badge">Open</span></summary><div style="margin-top:18px"><h3>Exact batch quantities</h3>${rows(d.i)}</div><div style="margin-top:20px"><h3>Do this step by step</h3>${steps(d.s)}</div></details>`).join('')}<article class="card"><h2>Final packing check</h2>${steps(g.finish)}</article><article class="card"><h2>Cool, store & reheat</h2>${steps(g.store)}</article>`;
  root.children[0]?.after(w);
 }
 document.querySelectorAll('[data-prep]').forEach(b=>b.addEventListener('click',()=>setTimeout(()=>add(b.dataset.prep),0)));
 setTimeout(()=>add('sun'),0);
})();